### ISSUE TITLE
UX: Unclear denomination description

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-bridge#13]
Hey, when entering the amount to bridge, it is not fully clear how much the user is bridging:

<img width="314" alt="image" src="https://github.com/aeternity/aepp-bridge/assets/11761828/bc6b70b6-1436-43ad-bfcd-a6b3347e1d0d">

the UI mentions 18 decimals, does that mean 

A. the user inputs 1 and 18 decimals are padded for him ( entering 1.8 means 1.8 * 10^18) or
B. the user needs to think of entering the 18 decimals, so 1800000000000000000 in order to transfer 1.8

Keep it up ! 👌

**Comment by yusufseyrek** [comment]
It's a normalized amount. So, when you type 1 it's 1, I will remove the text over there to prevent any confusion.

**Comment by nikita-fuchs** [comment]
Hold on a sec ! 

When "regular people" intend to transfer 1 USDT, they're not used to type 1000000000000000000. That is how it's implemented in most wallets.

After all, you're displaying the balance at the top also as 16 USDT, not 16000000000000000000, for example. We can't expect the user to know he has to type all the decimals. One suggestion: Show a tooltipp / text above the button reading something like "You are transfering XYZ USDT" or / and a modal confirming the amount before transfer, like other wallets do.

**Comment by yusufseyrek** [comment]
It's already made for regular people :) there is no need to add decimals right now. As I mentioned in my previous comment if you want to bridge 1 USDT, you just type 1.

**Comment by nikita-fuchs** [comment]
Right 👍 just make sure this is 100% clear to the user _somehow_ ;)
