### ISSUE TITLE
Provide 'What's next' information containing token contract addresses and guides

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-bridge#27]
Right now, the bridge does what it should but gives users no instructions what to do next after they've bridged something, so that they can handle the bridged funds. Even people from our team struggle. 

So when the average Joe bridges himself some wAE, he doesn't know how to handle this, unless somebody put something in place in the meantime. Therefore we must, after the success message, show an info panel:

In case the bridging is ae -> eth

" What's next ? 

In case you have not added [token name] to your wallet or it is not shown you there automatically by now, you might need to add it manually to your wallet. Read this: How do I add a token to [Metamask](https://support.metamask.io/de/metamask-portfolio/dashboard/how-to-import-a-token-in-metamask-portfolio/) , {add more wallets here, laurent should know the most popular others} ? If your wallet asks you for the contract address of [token name], you need to provide this one: `ak_abc/0x1337...' You can also check for the address again at {link at the top providing important information, as well as all contract addresses on all networks} "

In case the bridging is eth -> ae , we need to put this:

"What's next ? 

The recieved tokens should automatically be added to your Superhero Wallet, you can find them by opening your Superhero Wallet and clicking on the account you have put as the recipient of the tokens: 
<img width="720" alt="image" src="https://github.com/user-attachments/assets/31312cbb-dc09-49d9-991f-b25fffdc37ff">

If they have not appeared there yet, try refreshing the wallet or check in again in a few minutes. If you sitll have issues, please reach out in the [forum](https://forum.aeternity.com/) "

**Comment by yusufseyrek** [comment]
Hi @nikita-fuchs, as requested I've provided further instruction/information in the bridge action summary pop-up after the action was successfully sent:
<img width="2047" alt="Screenshot 2024-08-23 at 16 07 52" src="https://github.com/user-attachments/assets/878e7233-6960-454a-89ab-cc622828aaea">

Also, I improved the content and added a button to manually add the token to the wallet's token list with one click, as seen in the screenshot. Closing this issue now.

**Comment by nikita-fuchs** [comment]
hey, as mentioned in telegram: can you please add this information also somewhere where people can look it up afterwards, too, like the FAQs ? "I've bridged my tokens, what's next?" We will need another subpage listing all the token addresses so people have them at their disposal when neccessary. No need to add a separate link to them in the menu, just linking to it from that FAQ entry would be enough

**Comment by nikita-fuchs** [comment]
awesome job, thank you! I'll revisit later in case, but so far it's nice.
