### ISSUE TITLE
Remove aeternity foundation, add information about acurast.

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-bridge#36]
per request from high above.

**Comment by nikita-fuchs** [comment]
action taken: Requested nikola to clarify wording with legal team

**Comment by yusufseyrek** [comment]
I've talked to Nikola about this issue and updated the Terms and Conditions per his request. Also, with my last commit, I've added the `Powered by Acurast` remark with a link to acurast.com. 

Feel free to re-open if there are any other changes needed.

**Comment by nikita-fuchs** [comment]
Nice, thanks. Let's see if the legal people have anything to add to this, it should be good for now.
