### ISSUE TITLE
Ensure naming consistency for all tokens

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-bridge#39]
For every wrapped token contract on aeternity, the naming conventions shall be:

ORIGINAL:

Name: Tron
Symbol: TRX

Bridged: 
Name: aeTron
Symbol: aeTRX

**Comment by nikita-fuchs** [comment]
Action taken: Enquired with Acurast to rename contracts accordingly

**Comment by yusufseyrek** [comment]
@nikita-fuchs Bridge UI already has the suggested naming convention. See;
<img width="1261" alt="Screenshot 2024-08-15 at 16 37 55" src="https://github.com/user-attachments/assets/4cb12a65-b10a-4200-985c-07fcc987c4d1">

**Comment by nikita-fuchs** [comment]
Awesome @yusufseyrek 🚀 now waiting for https://github.com/aeternity/ae_mdw/issues/1899

**Comment by yusufseyrek** [comment]
Closing this issue as it's not related to the bridge front-end. The interface should continue to work as expected even after middleware changes. Feel free to re-open if anything breaks.
