### ISSUE TITLE
Having Superhero Wallet and MetaMask extension installed

### ISSUE THREAD

**Issue by dvdbak** [aeternity/aepp-bridge#50]
I do have the Superhero Wallet and Metamask extension installed in Brave, and if I select connect wallet I only get the MetaMask extension opened. It would be great if I could select which one I would like to connect.

**Comment by yusufseyrek** [comment]
Connection workflow for the wallet depends on the network selection from the UI. So, If you select "From Network" as "Aeternity" it should automatically prompt you to connect your Superhero Wallet.

**Comment by yusufseyrek** [comment]
I am closing this. Feel free to reopen if there are problems with the current flow or something new needed.
