### ISSUE TITLE
FAQ inconsistency

### ISSUE THREAD

**Issue by dvdbak** [aeternity/aepp-bridge#54]
https://ae-bridge.com/faq

I assume that bridgae is the proper name as it appears the most time.
Is: bridgeae
Expected: bridgae

Is: Aeternity (ae)
Expected: Aeternity (AE)
The coin used on aeternity blockchain is AE (always upper case)

**Comment by yusufseyrek** [comment]
Thanks for realizing this. Expected changes are live now.
