### ISSUE TITLE
Can't find definition of event emitted

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-bridge#6]
Hey @yusufseyrek , we might have to adjust a thing or two in the contract setup / sdk setup, shouldn't be a big thing.

<img width="951" alt="image" src="https://github.com/aeternity/aepp-bridge/assets/11761828/edbe6e70-3ae5-46d9-9b90-4012d8bb401c">

@davidyuk , it sounds like the contract call itself succeeded, but the contract emitted an event that was not known to the SDK, am I correct ?  

Quick-term solution: Can you please point where to set this option flag exactly @davidyuk ?
Mid-term solution: We should update the expected contract in this repo, I already asked for it.

**Comment by thepiwo** [comment]
add `{omitUnknown: true}`

**Comment by nikita-fuchs** [comment]
Thanks a lot @thepiwo , am I reading correct though that I can also add it to the contract setup options though? 

https://docs.aeternity.com/aepp-sdk-js/v13.2.2/api/classes/_internal_.Contract.html

**Comment by thepiwo** [comment]
haven't tried this

**Comment by davidyuk** [comment]
`omitUnknown` in `initializeContract` should also work.

> but the contract emitted an event that was not known to the SDK, am I correct ?

Yep, in particular it is not defined in ACI.
