### ISSUE TITLE
Can't close a notification, have to visit metamask site first.

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aepp-bridge#80]
I 've received a notification that Ethereum wallet not found. Can't close a notification, have to visit metamask site first.

Reproducible on: Chrome browser ver 131.0.6778.140
MacOS

https://github.com/user-attachments/assets/774181d6-39b8-40b3-b4c5-636a69696ec9

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Kendra162** [comment]
Hello,

Use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Saoiray405** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WB240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by yusufseyrek** [comment]
@Liubov-crypto I am working on delivering a fix. This was originally the intended behavior, but double-displaying seems like a bug. 

Also, we don't have any ticketing system or live support. Please be careful about those malicious actors posting phishing links here. Thanks.
