### ISSUE TITLE
Have to connect again connected wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aepp-bridge#82]
I've connected 2 wallets - EVM and Aeternity on transactions page, then I go to bridge and changed network from ETH to AE, I got popup that I have to connect a wallet, however my wallet is connected. 

Chrome ver. 131.0.6778.140
MacOS

https://github.com/user-attachments/assets/28915f34-2c6e-4064-8af8-6756ba910445

**Comment by Musk1045** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Lisa238-Dev** [comment]
Hello @Liubov-crypto 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID EVM170964
Please see the link below to our dedicated support line:
[MetaMask Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by yusufseyrek** [comment]
should be fixed now
