### ISSUE TITLE
Can't see WAE on my wallet balance in MetaMask wallet

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aepp-bridge#83]
I bridget AE to ETH and have to receive WAE on my metamask account, but can't see them, however Tx was successful. 

https://aescan.io/transactions/th_2g4VHZX8LLWRaAgJkuPpWEKANh5rV92k4CYPZaQKzMbEj93sEA

![wae](https://github.com/user-attachments/assets/1ea3e1e1-d97f-4fca-8dd1-b85184c2a5f5)

https://github.com/user-attachments/assets/179e0aac-94c3-45f5-8517-da14ed06e5cb

Chrome ver. 131.0.6778.140
MacOS

**Comment by Musk1045** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by Jaynelauren** [comment]
> I bridget AE to ETH and have to receive WAE on my metamask account, but can't see them, however Tx was successful.
> 
> https://aescan.io/transactions/th_2g4VHZX8LLWRaAgJkuPpWEKANh5rV92k4CYPZaQKzMbEj93sEA
> 
> ![wae](https://private-user-images.githubusercontent.com/69896204/397040625-1ea3e1e1-d97f-4fca-8dd1-b85184c2a5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NDM5NTcsIm5iZiI6MTczNDU0MzY1NywicGF0aCI6Ii82OTg5NjIwNC8zOTcwNDA2MjUtMWVhM2UxZTEtZDk3Zi00ZmNhLThkZDEtYjg1MTg0YzJhNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDE3NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YWRkOTY3YjczNmViMGU1YmMzODZmODUzNDM2MDBkNjNlMDNhNGU1ZDgxMzkzMjA2NGJjMzMzNjZkOTkyYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.p1sJb2e4hsEKk-kSOSyiTmSMPAXLTTyPnrLEJe0PIFk)
> 
>  2024-12-18.7.13.30.mov 
> Chrome ver. 131.0.6778.140 MacOS

Hello @Liubov-crypto ,

It seems you're encountering a transcript error. To get this resolved, please contact the  support team.

Make sure to provide the ticket ID **WAE7638** when reaching out. 
You can visit the support page here: [Metamask Wallet DApps Support Ticket Requests](https://thedappsupport.com/metmask). Simply click the live chat icon in the bottom corner to connect with a support agent for quick assistance.

Best regards.

**Comment by Kendra162** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.

**Comment by berryMo27** [comment]
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [AETERNITY SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by yusufseyrek** [comment]
Hey @Liubov-crypto, bridging funds is usually very fast (under a minute); but in your case, there was a delay because of the high gas price. Your tokens should be available in your wallet now.
